// <auto-generated />
namespace Inlamningsuppgift1_Dbt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MyMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201610261359436_MyMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
